language: php

php:
  - 5.6

before_script:
  - sudo apt-get update
  - sudo apt-get install libssh2-1-dev libssh2-php
  - pecl install -f ssh2 < .noninteractive
  - echo "extension=ssh2.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - php -m | grep ssh2
  - sudo useradd shunt
  - sudo passwd shunt < .shuntpwd
  - sudo mkdir /home/shunt
  - sudo chown shunt:shunt /home/shunt
  - sudo usermod -d /home/shunt shunt
  - composer install

script: phpunit --configuration phpunit.xml.dist
